name: v04
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  hero_common:
    path: ../hero_common
  sqlite3: ^2.9.2
  cli_spin: ^1.0.1
  ascii_art_converter: ^1.0.0
  
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
