name: shql
description: SHQL (Small, Handy, Quintessential Languageâ„¢) engine - parser, tokenizer, and runtime.
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  crypto: ^3.0.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

flutter:
  assets:
    - assets/
