name: hero_common
description: Shared domain logic for the Herodex superhero application.
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  path: ^1.9.0
  equatable: ^2.0.7
  uuid: ^4.5.1
  collection: ^1.19.1
  dart_dotenv: ^1.0.1
  http: ^1.5.0
  ascii_art_converter: ^1.0.0
  shql:
    path: ../shql

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
